wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.29
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: true
    python_version: 3.9.4
    t:
      1:
      - 1
      - 5
      2:
      - 1
      - 5
      3:
      - 1
      - 2
      4: 3.9.4
      5: 0.10.29
      8:
      - 1
      - 2
      - 5
